# Generated by Codex for IMP-003

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='audit_logs',
                to='organizations.organization',
            ),
        ),
    ]
