# Generated by Django 4.2.30 on 2026-04-29

import hashlib

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def populate_knowledge_document_created_by(apps, schema_editor):
    KnowledgeDocument = apps.get_model('knowledge_base', 'KnowledgeDocument')
    for knowledge_document in KnowledgeDocument.objects.select_related('knowledge_base').all():
        if knowledge_document.created_by_id is None:
            knowledge_document.created_by_id = knowledge_document.knowledge_base.created_by_id
            knowledge_document.save(update_fields=['created_by'])


def backfill_chunk_fields(apps, schema_editor):
    DocumentChunk = apps.get_model('knowledge_base', 'DocumentChunk')
    for chunk in DocumentChunk.objects.select_related('knowledge_document').all():
        if not chunk.content_hash:
            chunk.content_hash = hashlib.sha256((chunk.content or '').encode('utf-8')).hexdigest()
        if not chunk.char_count:
            chunk.char_count = len(chunk.content or '')
        if chunk.document_id is None:
            chunk.document_id = chunk.knowledge_document.document_id
        if chunk.metadata is None:
            chunk.metadata = {}
        chunk.save(update_fields=['content_hash', 'char_count', 'document', 'metadata'])


def normalize_retrieval_query_status(apps, schema_editor):
    RetrievalQuery = apps.get_model('knowledge_base', 'RetrievalQuery')
    RetrievalQuery.objects.exclude(status__in=['completed', 'no_sources', 'failed']).update(status='failed')


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('knowledge_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='knowledgedocument',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ['chunk_index', 'created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='retrievalquery',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='created_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='knowledge_documents',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='error_message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='source_type',
            field=models.CharField(
                choices=[('document', 'Document'), ('manual', 'Manual'), ('imported', 'Imported')],
                default='document',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='char_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='content_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='knowledge_chunks',
                to='documents.document',
            ),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RenameField(
            model_name='retrievalquery',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='retrievalquery',
            name='answer',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retrievalquery',
            name='sources_payload',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='retrievalquery',
            name='knowledge_base',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='queries',
                to='knowledge_base.knowledgebase',
            ),
        ),
        migrations.RunPython(
            populate_knowledge_document_created_by,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            backfill_chunk_fields,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            normalize_retrieval_query_status,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='knowledge_documents',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('failed', 'Failed')],
                default='pending',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='retrievalquery',
            name='status',
            field=models.CharField(
                choices=[('completed', 'Completed'), ('no_sources', 'No sources'), ('failed', 'Failed')],
                default='no_sources',
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('knowledge_document', 'chunk_index')},
        ),
    ]
