# Generated by Django 4.2.30 on 2026-04-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_sources_payload(apps, schema_editor):
    RetrievalQuery = apps.get_model('knowledge_base', 'RetrievalQuery')
    for query in RetrievalQuery.objects.all():
        payload = query.sources_payload
        if isinstance(payload, list):
            query.sources_payload = {
                'retrieval_method': 'textual',
                'sources_count': len(payload),
                'confidence': 'low' if payload else 'low',
                'sources': payload,
            }
            query.sources_count = len(payload)
            query.retrieval_method = 'textual'
            query.confidence = 'low'
            query.save(
                update_fields=[
                    'sources_payload',
                    'sources_count',
                    'retrieval_method',
                    'confidence',
                ]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('knowledge_base', '0002_functional_rag_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_status',
            field=models.CharField(
                choices=[('not_generated', 'Not generated'), ('generated', 'Generated'), ('failed', 'Failed')],
                default='not_generated',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='retrievalquery',
            name='confidence',
            field=models.CharField(default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='retrievalquery',
            name='retrieval_method',
            field=models.CharField(default='textual', max_length=30),
        ),
        migrations.AddField(
            model_name='retrievalquery',
            name='sources_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='retrievalquery',
            name='sources_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='IndexingJob',
            fields=[
                (
                    'id',
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('chunks_created', models.PositiveIntegerField(default=0)),
                ('chunks_deleted', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='knowledge_indexing_jobs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'document',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='knowledge_indexing_jobs',
                        to='documents.document',
                    ),
                ),
                (
                    'knowledge_base',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='indexing_jobs',
                        to='knowledge_base.knowledgebase',
                    ),
                ),
                (
                    'knowledge_document',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='indexing_jobs',
                        to='knowledge_base.knowledgedocument',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='knowledge_indexing_jobs',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                (
                    'id',
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('vector', models.JSONField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[('not_generated', 'Not generated'), ('generated', 'Generated'), ('failed', 'Failed')],
                        default='not_generated',
                        max_length=20,
                    ),
                ),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'chunk',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='embedding',
                        to='knowledge_base.documentchunk',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='chunk_embeddings',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.RunPython(migrate_sources_payload, migrations.RunPython.noop),
    ]
