# Generated by Django 4.2.30 on 2026-04-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_rag_phase_2'),
        ('organizations', '0002_alter_organization_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrieval_mode', models.CharField(choices=[('textual', 'Textual'), ('hybrid', 'Hybrid'), ('embeddings', 'Embeddings')], default='textual', max_length=20)),
                ('external_embeddings_enabled', models.BooleanField(default=False)),
                ('embedding_provider', models.CharField(blank=True, choices=[('local', 'Local'), ('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('other', 'Other')], max_length=40)),
                ('embedding_model', models.CharField(blank=True, max_length=120)),
                ('require_human_review_for_ai_answers', models.BooleanField(default=True)),
                ('allow_document_content_to_external_provider', models.BooleanField(default=False)),
                ('max_sources_per_answer', models.PositiveIntegerField(default=5)),
                ('min_confidence_threshold', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rag_settings', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rag_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['organization_id']},
        ),
        migrations.CreateModel(
            name='EmbeddingAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(choices=[('requested', 'Requested'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('completed', 'Completed')], max_length=20)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='ok', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embedding_audit_logs', to='knowledge_base.documentchunk')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embedding_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('knowledge_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embedding_audit_logs', to='knowledge_base.knowledgedocument')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embedding_audit_logs', to='organizations.organization')),
            ],
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
