# Generated by Django 4.2.30 on 2026-04-28 13:52

from django.db import migrations, models


def migrate_starter_to_free(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    Organization.objects.filter(plan="starter").update(plan="free")


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_starter_to_free, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="organization",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("solo", "Solo"),
                    ("growth", "Escritório"),
                    ("enterprise", "Enterprise"),
                ],
                default="free",
                max_length=50,
            ),
        ),
    ]
