# Generated by Django 4.2.30 on 2026-04-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at", "id"]},
        ),
    ]
