# Generated by Django 4.2.30 on 2026-04-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legal_finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientinvoice",
            options={"ordering": ["-created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="legalfee",
            options={"ordering": ["-created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="paymentrecord",
            options={"ordering": ["-created_at", "id"]},
        ),
    ]
