# Generated by Django 4.2.30 on 2026-04-24 18:36

from django.db import migrations, models
import django.db.models.deletion
import jurisai.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("law_cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("petition", "Petição"),
                            ("contract", "Contrato"),
                            ("evidence", "Prova"),
                            ("internal", "Documento interno"),
                        ],
                        max_length=40,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=jurisai.utils.document_upload_path,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "law_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="law_cases.lawcase",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "-created_at"],
                "unique_together": {("law_case", "version")},
            },
        ),
    ]
