export const endpoints = {
  health: {
    public: "/health/",
    api: "/api/v1/health/",
  },
  auth: {
    login: "/api/v1/auth/token/",
    refresh: "/api/v1/auth/token/refresh/",
    verify: "/api/v1/auth/token/verify/",
    me: "/api/v1/users/me/",
    profile: "/api/v1/users/profile/",
    users: "/api/v1/users/",
    changePassword: "/api/v1/users/change-password/",
  },
  organizations: {
    list: "/api/v1/organizations/",
    plans: "/api/v1/organizations/plans/",
  },
  cases: {
    list: "/api/v1/cases/",
    detail: (id: string) => `/api/v1/cases/${id}/`,
  },
  clients: {
    list: "/api/v1/users/",
    detail: (id: string) => `/api/v1/users/${id}/`,
  },
  documents: {
    list: "/api/v1/documents/",
    detail: (id: string) => `/api/v1/documents/${id}/`,
  },
  deadlines: {
    list: "/api/v1/deadlines/",
    detail: (id: string) => `/api/v1/deadlines/${id}/`,
    complete: (id: string) => `/api/v1/deadlines/${id}/complete/`,
  },
  tasks: {
    list: "/api/v1/tasks/",
  },
  dashboard: {
    summary: "/api/v1/dashboard/summary/",
    deadlines: "/api/v1/dashboard/deadlines/",
    tasks: "/api/v1/dashboard/tasks/",
    documents: "/api/v1/dashboard/documents/",
    financial: "/api/v1/dashboard/financial/",
  },
  clientPortal: {
    cases: "/api/v1/client-portal/cases/",
    documents: "/api/v1/client-portal/documents/",
    messages: "/api/v1/client-portal/messages/",
  },
  calendar: {
    events: "/api/v1/calendar/events/",
    upcoming: "/api/v1/calendar/events/upcoming/",
    month: "/api/v1/calendar/events/month/",
  },
  legalFinance: {
    summary: "/api/v1/legal-finance/summary/",
    invoices: "/api/v1/legal-finance/invoices/",
    fees: "/api/v1/legal-finance/fees/",
    expenses: "/api/v1/legal-finance/expenses/",
    payments: "/api/v1/legal-finance/payments/",
  },
  knowledgeBase: {
    list: "/api/v1/knowledge-base/",
    detail: (id: string) => `/api/v1/knowledge-base/${id}/`,
    settings: "/api/v1/knowledge-base/settings/",
    documents: "/api/v1/knowledge-base/documents/",
    queries: "/api/v1/knowledge-base/queries/",
    indexingJobs: "/api/v1/knowledge-base/indexing-jobs/",
    embeddingAuditLogs: "/api/v1/knowledge-base/embedding-audit-logs/",
    stats: (id: string) => `/api/v1/knowledge-base/${id}/stats/`,
    search: (id: string) => `/api/v1/knowledge-base/${id}/search/`,
    ask: (id: string) => `/api/v1/knowledge-base/${id}/ask/`,
    indexDocument: (id: string) => `/api/v1/knowledge-base/${id}/index-document/`,
    prepareEmbeddings: (id: string) => `/api/v1/knowledge-base/${id}/prepare-embeddings/`,
  },
  ocr: {
    jobs: "/api/v1/ocr/jobs/",
    results: "/api/v1/ocr/results/",
    pageResults: "/api/v1/ocr/page-results/",
    pipelines: "/api/v1/ocr/pipelines/",
    settings: "/api/v1/ocr/settings/",
    auditLogs: "/api/v1/ocr/audit-logs/",
    runDocument: (documentId: string) => `/api/v1/ocr/documents/${documentId}/run/`,
    runAdvancedDocument: (documentId: string) =>
      `/api/v1/ocr/documents/${documentId}/advanced-run/`,
    resultPages: (id: string) => `/api/v1/ocr/results/${id}/pages/`,
    applyResult: (id: string) => `/api/v1/ocr/results/${id}/apply-to-document/`,
    runKnowledgeBasePipeline: "/api/v1/ocr/pipelines/run-knowledge-base-pipeline/",
  },
  ai: {
    generatePetition: "/api/v1/ai/generate-petition/",
    summarizeDocument: "/api/v1/ai/summarize-document/",
    analyzeRisk: "/api/v1/ai/analyze-risk/",
    searchJurisprudence: "/api/v1/ai/search-jurisprudence/",
    draftContract: "/api/v1/ai/draft-contract/",
    reviewDocument: "/api/v1/ai/review-document/",
    history: "/api/v1/ai/history/",
  },
  billing: {
    payments: "/api/v1/payments/",
    subscriptions: "/api/v1/subscriptions/",
    invoices: "/api/v1/invoices/",
    webhook: "/api/v1/webhook/",
  },
} as const;
