# Generated by Django 4.2.30 on 2026-04-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ocrjob",
            options={"ordering": ["-created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="ocrresult",
            options={"ordering": ["-created_at", "id"]},
        ),
        migrations.RemoveField(
            model_name="ocrresult",
            name="confidence",
        ),
        migrations.AddField(
            model_name="ocrjob",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ocrjob",
            name="extraction_method",
            field=models.CharField(
                choices=[
                    ("txt", "TXT"),
                    ("pdf_text", "PDF text"),
                    ("docx_text", "DOCX text"),
                    ("unsupported", "Unsupported"),
                ],
                default="unsupported",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ocrjob",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ocrjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ocrjob",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="char_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ocr_results",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="ocrresult",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="ocrjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
