# Generated by Django 4.2.30 on 2026-04-29 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("knowledge_base", "0004_rag_governance"),
        ("documents", "0001_initial"),
        ("organizations", "0002_alter_organization_plan"),
        ("ocr", "0002_alter_ocrjob_options_alter_ocrresult_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRKnowledgeBasePipelineRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("ocr", "OCR"),
                            ("apply_to_document", "Apply to document"),
                            ("index_document", "Index document"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=30,
                    ),
                ),
                ("update_document_content", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocr_knowledge_base_pipeline_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocr_knowledge_base_pipeline_runs",
                        to="documents.document",
                    ),
                ),
                (
                    "indexing_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocr_pipeline_runs",
                        to="knowledge_base.indexingjob",
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocr_pipeline_runs",
                        to="knowledge_base.knowledgebase",
                    ),
                ),
                (
                    "knowledge_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocr_pipeline_runs",
                        to="knowledge_base.knowledgedocument",
                    ),
                ),
                (
                    "ocr_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_base_pipeline_runs",
                        to="ocr.ocrjob",
                    ),
                ),
                (
                    "ocr_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_base_pipeline_runs",
                        to="ocr.ocrresult",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocr_knowledge_base_pipeline_runs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
    ]
