# Generated by Django 4.2.30 on 2026-04-29 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_organization_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0001_initial"),
        ("ocr", "0003_ocrknowledgebasepipelinerun"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advanced_ocr_enabled", models.BooleanField(default=False)),
                ("external_ocr_enabled", models.BooleanField(default=False)),
                (
                    "allow_document_content_to_external_ocr_provider",
                    models.BooleanField(default=False),
                ),
                (
                    "preferred_ocr_provider",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("tesseract", "Tesseract"),
                            ("google_vision", "Google Vision"),
                            ("azure_vision", "Azure Vision"),
                            ("aws_textract", "AWS Textract"),
                            ("other", "Other"),
                        ],
                        default="local",
                        max_length=40,
                    ),
                ),
                ("preferred_ocr_model", models.CharField(blank=True, max_length=120)),
                (
                    "image_ocr_mode",
                    models.CharField(
                        choices=[
                            ("disabled", "Disabled"),
                            ("local_placeholder", "Local placeholder"),
                            ("external", "External"),
                        ],
                        default="disabled",
                        max_length=30,
                    ),
                ),
                (
                    "scanned_pdf_ocr_mode",
                    models.CharField(
                        choices=[
                            ("disabled", "Disabled"),
                            ("local_placeholder", "Local placeholder"),
                            ("external", "External"),
                        ],
                        default="disabled",
                        max_length=30,
                    ),
                ),
                ("require_human_review", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocr_settings",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocr_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["organization_id"],
            },
        ),
        migrations.CreateModel(
            name="OCRAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=120)),
                ("mode", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocr_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocr_audit_logs",
                        to="documents.document",
                    ),
                ),
                (
                    "ocr_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="ocr.ocrjob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocr_audit_logs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
    ]
