# Generated by Django 4.2.30 on 2026-04-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0004_ocrsettings_ocrauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocrjob",
            name="extraction_method",
            field=models.CharField(
                choices=[
                    ("txt", "TXT"),
                    ("pdf_text", "PDF text"),
                    ("docx_text", "DOCX text"),
                    ("image_local", "Local image OCR"),
                    ("scanned_pdf_local", "Local scanned PDF OCR"),
                    ("unsupported", "Unsupported"),
                ],
                default="unsupported",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ocrsettings",
            name="image_ocr_mode",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("local", "Local"),
                    ("local_placeholder", "Local placeholder"),
                    ("external", "External"),
                ],
                default="disabled",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="ocrsettings",
            name="scanned_pdf_ocr_mode",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("local", "Local"),
                    ("local_placeholder", "Local placeholder"),
                    ("external", "External"),
                ],
                default="disabled",
                max_length=30,
            ),
        ),
    ]
