# Generated by Django 4.2.30 on 2026-04-29 18:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_organization_plan"),
        ("documents", "0001_initial"),
        ("ocr", "0005_alter_ocrjob_extraction_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrsettings",
            name="max_ocr_chars_output",
            field=models.PositiveIntegerField(default=200000),
        ),
        migrations.AddField(
            model_name="ocrsettings",
            name="max_ocr_file_size_mb",
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name="ocrsettings",
            name="max_scanned_pdf_pages",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="ocrsettings",
            name="store_page_level_ocr",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="OCRPageResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("extracted_text", models.TextField(blank=True)),
                ("char_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocr_page_results",
                        to="documents.document",
                    ),
                ),
                (
                    "ocr_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_results",
                        to="ocr.ocrjob",
                    ),
                ),
                (
                    "ocr_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_results",
                        to="ocr.ocrresult",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocr_page_results",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number", "created_at", "id"],
            },
        ),
    ]
